name: Builder

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aarch64:
    runs-on: self-hosted
    timeout-minutes: 900
    steps:      
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1
        with:
          platforms: arm64
      
      - name: Setup ROS cross compiler
        run: |
          sudo apt-get update && sudo apt-get install -y wget git python3-pip qemu-user-static
          sudo -H pip3 install ros_cross_compile vcstool
          mkdir -p ~/ros2_foxy/src
          cp default.yaml ~/ros2_foxy
          cd ~/ros2_foxy
          wget https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos
          wget https://raw.githubusercontent.com/robotique-ecam/cdfr/master/ros_ws.repos
          vcs import src < ros2.repos
          vcs import src < ros_ws.repos
          
      - name: Build ros2 foxy for aarch64
        timeout-minutes: 900
        run: |
          ros_cross_compile \
          ~/ros2_foxy/ \
          --arch aarch64 \
          --os debian \
          --rosdistro foxy \
          --skip-rosdep-keys "catkin console_bridge fastcdr fastrtps gazebo_ros_pkgs libceres-dev rti-connext-dds-5.3.1 urdfdom_headers"
          
      - name: Package and upload built base-packages
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ~/ros2_foxy/install_aarch64
          if-no-files-found: error
          retention_days: 90
